codecov:
  require_ci_to_pass: true

coverage:
  range: 70..100
  round: down
  precision: 2

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
